// Static seed data for consistent generation
export const companies = [
  "TechCorp Solutions",
  "InnovateSoft",
  "DataFlow Systems",
  "CloudScale Technologies",
  "NextGen Software",
  "AI Solutions Inc",
  "Digital Dynamics",
  "ByteForge Technologies",
  "CodeCraft Labs",
  "Quantum Computing Co",
];

export const locations = [
  "San Francisco, CA",
  "New York, NY",
  "Austin, TX",
  "Seattle, WA",
  "Boston, MA",
  "Remote",
  "Chicago, IL",
  "Denver, CO",
  "Los Angeles, CA",
  "Atlanta, GA",
];

export const jobTypes = ["full-time", "part-time", "contract"];

export const skillSets = {
  frontend: [
    "React",
    "TypeScript",
    "JavaScript",
    "HTML",
    "CSS",
    "Redux",
    "NextJS",
    "Vue",
    "Angular",
    "TailwindCSS",
  ],
  backend: [
    "Node.js",
    "Python",
    "Java",
    "Spring Boot",
    "GraphQL",
    "REST APIs",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "Docker",
  ],
  devops: [
    "AWS",
    "Azure",
    "Kubernetes",
    "Docker",
    "Jenkins",
    "Terraform",
    "CI/CD",
    "Linux",
    "Git",
    "Monitoring",
  ],
  mobile: [
    "React Native",
    "iOS",
    "Swift",
    "Android",
    "Kotlin",
    "Flutter",
    "Mobile Testing",
    "App Store",
    "Play Store",
    "Cross-Platform",
  ],
  data: [
    "Python",
    "SQL",
    "Data Analysis",
    "Machine Learning",
    "Pandas",
    "NumPy",
    "Scikit-learn",
    "TensorFlow",
    "Data Visualization",
    "Big Data",
  ],
};

export const jobTitles = {
  frontend: [
    "Frontend Engineer",
    "UI Developer",
    "React Developer",
    "Frontend Architect",
    "UI/UX Developer",
  ],
  backend: [
    "Backend Engineer",
    "API Developer",
    "Java Developer",
    "Node.js Developer",
    "Python Developer",
  ],
  devops: [
    "DevOps Engineer",
    "Cloud Engineer",
    "SRE",
    "Infrastructure Engineer",
    "Platform Engineer",
  ],
  mobile: [
    "Mobile Developer",
    "iOS Engineer",
    "Android Developer",
    "React Native Developer",
    "Mobile App Engineer",
  ],
  data: [
    "Data Engineer",
    "Data Scientist",
    "Machine Learning Engineer",
    "AI Developer",
    "Data Analyst",
  ],
};

export const jobDescriptionTemplates = [
  "We are seeking a talented {role} to join our growing team. The ideal candidate will have strong experience with {skills} and a passion for building scalable solutions. You'll work on challenging projects using cutting-edge technologies while collaborating with a diverse team.",
  "Join our innovative team as a {role}! We're looking for someone skilled in {skills} to help build next-generation applications. You'll have the opportunity to work on impactful projects and grow your technical expertise.",
  "Exciting opportunity for a {role} to work on our core products. Strong knowledge of {skills} required. You'll be responsible for designing, implementing, and maintaining critical systems while working in an agile environment.",
];

export const firstNames = [
  "James",
  "Mary",
  "John",
  "Patricia",
  "Robert",
  "Jennifer",
  "Michael",
  "Linda",
  "William",
  "Elizabeth",
  "David",
  "Barbara",
  "Richard",
  "Susan",
  "Joseph",
  "Jessica",
  "Thomas",
  "Sarah",
  "Charles",
  "Karen",
  "Wei",
  "Liu",
  "Mohammed",
  "Sofia",
  "Isabella",
  "Maria",
  "José",
  "Ana",
  "Miguel",
  "Elena",
  "Raj",
  "Priya",
];

export const lastNames = [
  "Smith",
  "Johnson",
  "Williams",
  "Brown",
  "Jones",
  "Garcia",
  "Miller",
  "Davis",
  "Rodriguez",
  "Martinez",
  "Hernandez",
  "Lopez",
  "Gonzalez",
  "Wilson",
  "Anderson",
  "Thomas",
  "Taylor",
  "Moore",
  "Jackson",
  "Martin",
  "Lee",
  "Patel",
  "Kim",
  "Nguyen",
  "Chen",
  "Yang",
  "Kumar",
  "Singh",
  "Wu",
  "Zhou",
  "Zhao",
  "Yamamoto",
];

export const universities = [
  "Stanford University",
  "MIT",
  "University of California, Berkeley",
  "Georgia Tech",
  "Carnegie Mellon University",
  "University of Washington",
  "University of Texas at Austin",
  "University of Illinois",
  "University of Michigan",
  "Purdue University",
];

export const previousCompanies = [
  "Google",
  "Microsoft",
  "Apple",
  "Amazon",
  "Meta",
  "Netflix",
  "Twitter",
  "LinkedIn",
  "Uber",
  "Airbnb",
  "Oracle",
  "IBM",
  "Intel",
  "Adobe",
  "Salesforce",
];

// Assessment question templates for different roles
export const assessmentTemplates = {
  coding: [
    {
      type: "code",
      text: "Implement a function that finds the first non-repeating character in a string",
      options: null,
      answer: null,
    },
    {
      type: "code",
      text: "Write a function to detect a cycle in a linked list",
      options: null,
      answer: null,
    },
    {
      type: "multiple-choice",
      text: "What is the time complexity of quicksort in the average case?",
      options: ["O(n)", "O(n log n)", "O(n²)", "O(2ⁿ)"],
      answer: "O(n log n)",
    },
  ],
  system_design: [
    {
      type: "long-text",
      text: "Design a URL shortening service like bit.ly. Consider scalability, data storage, and handling redirects.",
      options: null,
      answer: null,
    },
    {
      type: "multiple-choice",
      text: "Which database would be most appropriate for a real-time chat application?",
      options: ["PostgreSQL", "MongoDB", "Redis", "Cassandra"],
      answer: "MongoDB",
    },
  ],
  behavioral: [
    {
      type: "long-text",
      text: "Describe a challenging project you worked on and how you overcame obstacles.",
      options: null,
      answer: null,
    },
    {
      type: "short-text",
      text: "What are your career goals for the next 5 years?",
      options: null,
      answer: null,
    },
  ],
};
